# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Enemy.create(:name => "駆逐艦イ級flagship", :hp => 39, :fire => 32, :torpedo => 60, :defence => 24, :equipment_type => "3")
Enemy.create(:name => "駆逐艦イ級後期型", :hp => 35, :fire => 40, :torpedo => 60, :defence => 22, :equipment_type => "3")
Enemy.create(:name => "駆逐艦ロ級", :hp => 22, :fire => 9, :torpedo => 16, :defence => 6, :equipment_type => "")
Enemy.create(:name => "駆逐艦ロ級elite", :hp => 35, :fire => 22, :torpedo => 37, :defence => 14, :equipment_type => "2")
Enemy.create(:name => "駆逐艦ロ級flagship", :hp => 43, :fire => 35, :torpedo => 70, :defence => 24, :equipment_type => "2")
Enemy.create(:name => "駆逐艦ロ級後期型", :hp => 37, :fire => 40, :torpedo => 66, :defence => 26, :equipment_type => "3")
Enemy.create(:name => "駆逐艦ハ級", :hp => 24, :fire => 8, :torpedo => 18, :defence => 7, :equipment_type => "2")
Enemy.create(:name => "駆逐艦ハ級elite", :hp => 40, :fire => 17, :torpedo => 42, :defence => 16, :equipment_type => "2")
Enemy.create(:name => "駆逐艦ハ級flagship", :hp => 47, :fire => 32, :torpedo => 70, :defence => 27, :equipment_type => "2")
Enemy.create(:name => "駆逐艦ハ級後期型", :hp => 38, :fire => 46, :torpedo => 82, :defence => 29, :equipment_type => "2")
Enemy.create(:name => "駆逐艦ニ級", :hp => 28, :fire => 10, :torpedo => 36, :defence => 9, :equipment_type => "")
Enemy.create(:name => "駆逐艦ニ級elite", :hp => 45, :fire => 22, :torpedo => 50, :defence => 18, :equipment_type => "2")
Enemy.create(:name => "駆逐艦ニ級後期型", :hp => 40, :fire => 50, :torpedo => 94, :defence => 33, :equipment_type => "2")
Enemy.create(:name => "軽巡ホ級", :hp => 33, :fire => 16, :torpedo => 24, :defence => 15, :equipment_type => "")
Enemy.create(:name => "軽巡ホ級elite", :hp => 48, :fire => 32, :torpedo => 40, :defence => 30, :equipment_type => "")
Enemy.create(:name => "軽巡ホ級flagship", :hp => 53, :fire => 44, :torpedo => 72, :defence => 36, :equipment_type => "3")
Enemy.create(:name => "軽巡へ級", :hp => 36, :fire => 19, :torpedo => 28, :defence => 18, :equipment_type => "")
Enemy.create(:name => "軽巡へ級elite", :hp => 52, :fire => 37, :torpedo => 48, :defence => 32, :equipment_type => "")
Enemy.create(:name => "軽巡へ級flagship", :hp => 57, :fire => 51, :torpedo => 80, :defence => 39, :equipment_type => "3")
Enemy.create(:name => "軽巡ト級", :hp => 39, :fire => 27, :torpedo => 30, :defence => 20, :equipment_type => "")
Enemy.create(:name => "軽巡ト級elite", :hp => 55, :fire => 39, :torpedo => 50, :defence => 36, :equipment_type => "")
Enemy.create(:name => "軽巡ツ級", :hp => 48, :fire => 62, :torpedo => 84, :defence => 55, :equipment_type => "1")
Enemy.create(:name => "軽巡ツ級elite", :hp => 58, :fire => 68, :torpedo => 92, :defence => 68, :equipment_type => "1")
Enemy.create(:name => "雷巡チ級", :hp => 48, :fire => 20, :torpedo => 52, :defence => 22, :equipment_type => "4")
Enemy.create(:name => "雷巡チ級elite", :hp => 50, :fire => 38, :torpedo => 82, :defence => 34, :equipment_type => "4")
Enemy.create(:name => "雷巡チ級flagship", :hp => 70, :fire => 53, :torpedo => 140, :defence => 60, :equipment_type => "4")
Enemy.create(:name => "重巡リ級", :hp => 58, :fire => 40, :torpedo => 34, :defence => 28, :equipment_type => "2")
Enemy.create(:name => "重巡リ級elite", :hp => 60, :fire => 69, :torpedo => 42, :defence => 60, :equipment_type => "1")
Enemy.create(:name => "重巡リ級flagship", :hp => 76, :fire => 79, :torpedo => 58, :defence => 70, :equipment_type => "2")
Enemy.create(:name => "重巡リ級改flagship", :hp => 88, :fire => 104, :torpedo => 90, :defence => 80, :equipment_type => "2")
Enemy.create(:name => "重巡リ級", :hp => 80, :fire => 89, :torpedo => 76, :defence => 68, :equipment_type => "2")
Enemy.create(:name => "重巡リ級elite", :hp => 88, :fire => 95, :torpedo => 84, :defence => 82, :equipment_type => "1")
Enemy.create(:name => "軽母ヌ級", :hp => 65, :fire => 65, :torpedo => 0, :defence => 25, :equipment_type => "0")
Enemy.create(:name => "軽母ヌ級elite", :hp => 70, :fire => 65, :torpedo => 0, :defence => 35, :equipment_type => "0")
Enemy.create(:name => "軽母ヌ級flagship", :hp => 84, :fire => 113, :torpedo => 0, :defence => 70, :equipment_type => "0")
Enemy.create(:name => "空母ヲ級elite", :hp => 88, :fire => 74, :torpedo => 0, :defence => 55, :equipment_type => "0")
Enemy.create(:name => "空母ヲ級flagship", :hp => 96, :fire => 112, :torpedo => 0, :defence => 80, :equipment_type => "0")
Enemy.create(:name => "空母ヲ級flagship", :hp => 96, :fire => 112, :torpedo => 0, :defence => 80, :equipment_type => "0")
Enemy.create(:name => "空母ヲ級flagship(新型搭載)", :hp => 96, :fire => 152, :torpedo => 0, :defence => 80, :equipment_type => "0")
Enemy.create(:name => "戦艦ル級", :hp => 90, :fire => 92, :torpedo => 0, :defence => 70, :equipment_type => "1")
Enemy.create(:name => "戦艦ル級elite", :hp => 90, :fire => 132, :torpedo => 0, :defence => 85, :equipment_type => "1")
Enemy.create(:name => "戦艦ル級flagship", :hp => 98, :fire => 130, :torpedo => 0, :defence => 99, :equipment_type => "1")
Enemy.create(:name => "戦艦ル級改flagship", :hp => 130, :fire => 150, :torpedo => 0, :defence => 130, :equipment_type => "2")
Enemy.create(:name => "戦艦タ級", :hp => 84, :fire => 97, :torpedo => 0, :defence => 80, :equipment_type => "1")
Enemy.create(:name => "戦艦タ級elite", :hp => 88, :fire => 117, :torpedo => 0, :defence => 88, :equipment_type => "1")
Enemy.create(:name => "戦艦タ級flagship", :hp => 90, :fire => 125, :torpedo => 0, :defence => 96, :equipment_type => "1")
Enemy.create(:name => "戦艦レ級", :hp => 180, :fire => 117, :torpedo => 110, :defence => 110, :equipment_type => "1")
Enemy.create(:name => "戦艦レ級elite", :hp => 270, :fire => 157, :torpedo => 138, :defence => 130, :equipment_type => "1")
Enemy.create(:name => "輸送ワ級", :hp => 70, :fire => 0, :torpedo => 0, :defence => 10, :equipment_type => "0")
Enemy.create(:name => "輸送ワ級elite", :hp => 80, :fire => 18, :torpedo => 0, :defence => 35, :equipment_type => "0")
Enemy.create(:name => "輸送ワ級flagship", :hp => 130, :fire => 62, :torpedo => 0, :defence => 65, :equipment_type => "0")
Enemy.create(:name => "浮遊要塞", :hp => 88, :fire => 58, :torpedo => 40, :defence => 44, :equipment_type => "0")
Enemy.create(:name => "護衛要塞", :hp => 66, :fire => 63, :torpedo => 45, :defence => 50, :equipment_type => "0")
